export const CLIENT_AUTH_ERROR = 'CLIENT_AUTH_ERROR';
export const CLIENT_ERROR = 'CLIENT_ERROR';
export const CLIENT_VALIDATION_ERROR = 'CLIENT_VALIDATION_ERROR';
export const SERVER_ERROR = 'SERVER_ERROR';
